fastlane_version '2.53.1'

#before_all do
  #ensure_git_branch
  #ensure_git_status_clean
  #git_pull
#end

#platform :ios do
   # iOS Lanes
#end

platform :android do
  # Android Lanes
  desc 'Build the Android application.'
  lane :build do
    sh "npm i"
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
    #push_to_git_remote
  end

end